spring.application.name=grupFly
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://${DB_HOME}/grupFly
spring.datasource.username=${DB_USERPOSTGRES}
spring.datasource.password=${DB_PASSWORDPOSTGRES}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.dialect=HSQL